# Generated by Django 4.1 on 2022-08-05 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='likes_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
